### ISSUE TITLE
Arch Packaging

### ISSUE THREAD

**Issue by ibnuda** [2mol/pboy#22]
I read your post on https://lobste.rs/s/atmus0/paperboy_v1_1_released#c_qnouvb about packaging. 
Arch Travis (https://github.com/mikkeloscar/arch-travis) seems to solve one of the problem.

**Comment by 2mol** [comment]
Nice, thank you for the tip, will do some experiments with it!

**Comment by j605** [comment]
I created an AUR package, https://aur.archlinux.org/packages/paperboy/

**Comment by 2mol** [comment]
Cool, thank you very much @j605 for doing that!

Is it usual to have the package compiled from source? Or is it also an option to use the compiled release?

**Comment by ibnuda** [comment]
Usually, people say that aur (and by compiling from source) is one of arch' strength. So yeah, put it in aur (and let the users compile it themselves) and you're good to go.

**Comment by j605** [comment]
> Is it usual to have the package compiled from source? Or is it also an option to use the compiled release?

There is an option to just repackage a binary release and the convention is to name it `pkgname-bin`. Although I would prefer to build from source unless it is difficult to package or takes a lot of resources to compile. It was neither in this case :)

**Comment by 2mol** [comment]
Super, then I'll put it in the readme. Is there a way we can coordinate when I release a new version?

**Comment by 2mol** [comment]
Cool, thank you very much for your contribution!
