### ISSUE TITLE
Viewer launch is blocking

### ISSUE THREAD

**Issue by n-st** [2mol/pboy#26]
Currently, paperboy waits for the external viewer command to exit before returning: https://github.com/2mol/pboy/blob/6f4dff94beafc720c92a8c464e9526f1afaaf207/src/Lib.hs#L187
It would be useful to be able to view multiple files in parallel.

(This could be done by changing XDG file associations and registering a forking program as the default viewer, but hopefully this can be solved more cleanly in paperboy itself.)

**Comment by 2mol** [comment]
Thanks for noticing this, I didn't know it was blocking. Maybe on mac it's different than on linux, I'll test.

If you have a Haskell environment installed, then it would be cool if you could try to change the line you highlighted and send me a PR. It doesn't need to be perfect, we'll merge it into dev and continue working from there. If you have questions about how to do any of the above, I'm here to explain stuff!

**Comment by 2mol** [comment]
merged PR, will release in 1.3
