### ISSUE TITLE
Length limitation

### ISSUE THREAD

**Issue by n-st** [2mol/pboy#27]
Would it be possible to increase the length limit for titles?
Currently, any suggestions beyond 64 characters are discarded:
https://github.com/2mol/pboy/blob/master/src/Lib.hs#L119
I just tried to rename a thesis on "Parallelizing a Many-Objective Sorting Algorithm for Test Generation" — which foundered on the 68-character title. :(

**Comment by 2mol** [comment]
Good point, the restriction is totally arbitrary. Want to send me a pull request changing it to 100 or 128 or something?

**Comment by n-st** [comment]
I tried to find some information on common paper title lengths, but it seems there's [huge variability there](https://blog.oup.com/2018/09/efficient-titles-research-articles/)…

Maybe we could go at it from the other end: [how long can the resulting filename be](https://en.wikipedia.org/wiki/Comparison_of_file_systems#Limits)?
That would be 255 bytes for most Unixoid filesystems, minus 4 for the extension (`.pdf`), so 251 bytes. Enough even for the "Cost-effectiveness of transcatheter aortic valve replacement compared with surgical aortic valve replacement in high-risk patients with severe aortic stenosis: Results of the PARTNER (Placement of Aortic Transcatheter Valves) trial (Cohort A)" from the article above. ;)

Strictly speaking, `Text.length` gives us *characters*, not *bytes*, so we might overshoot the 251 byte limit — but that seems like a fairly rare case.
And we'll run into the [width limit of the dialog window](https://github.com/2mol/pboy/blob/master/src/UI.hs#L486), but that should also be rare enough to ignore (I assume it will just crop the text before it overflows the box).

I'll go right ahead with a pull request when Github finishes forking the repo — apparently their backend is a bit overloaded at the moment…

Sorry for the avalanche of issues, by the way — I just dumped in a bunch of ideas before going to bed last night… I'll see if I can implement some of them myself (haven't used Haskell much so far). Thanks a lot for your helpful tool already! :)

**Comment by 2mol** [comment]
Awesome, I love that you researched the unix filename limit in such detail! No need to apologise for opening issues, you're doing everybody a favour by testing and inspecting the tool so thoroughly.

Thanks for the PR, we'll merge it into dev to prep for the next release.
