### ISSUE TITLE
Configurable word separator (instead of hardcoded '_')

### ISSUE THREAD

**Issue by n-st** [2mol/pboy#28]
It's a matter of preference, but I think it would be useful to have different options for the automatically inserted word separator: `_` is very compatible, but reduces readability; ` ` (space) is readable, but requires escaping in shells; some people might even prefer `.` or `-`…
Perhaps this could just be an option in the config file?

**Comment by 2mol** [comment]
Yup, I almost implemented that in the last release, but didn't for some reason. I'll bump it up on the roadmap: https://github.com/2mol/pboy/blob/master/Roadmap.md

**Comment by 2mol** [comment]
merged into dev, will be released in 1.3
