### ISSUE TITLE
why libtinfo5 and not the libtinfo6 from the current ncurses ?

### ISSUE THREAD

**Issue by m040601** [2mol/pboy#42]
> I am still looking to package Paperboy for Debian/Ubuntu, **Arch**/Manjaro, Fedora, Doge Linux, or whatever else people install these days.
> Any pointers or help with regards to generate .deb, .rpm, **AUR PKGBUILD,** etc is appreciated.

Hi, this looks like a very interesting program. It has a great appeal to cli power users.
I've heard about it for quite some time but I never managed to install it and compare it to the others I have. I'm on Archlinux, and I would really like to see a **BINARY** paperboy version one day on it.

Yes, I know that:
> On Debian 10, for example, pboy doesn't work 
> unless the libtinfo5 package is installed
> sudo apt install libtinfo5

But that's only Debian, a very conservative distribution. And installling some extra legacy. There isnt' and there will never be an old legacy ncurses library being **officially distributed** on ArchLinux. It would only bork a modern system. I also doubt any Arch user would try  to personally install an older version, just because of one package, and mess up his system.

We do have another paperboy version on Arch,
https://aur.archlinux.org/packages/paperboy
But it's a **SOURCE** version of paperboy. That means (like many other haskell software) you have to download more than half a gigabyte of ghc and haskell libraries just to compile it.

There is also a possibilty to distribute a user contributed (not official) **BINARY**
as an AUR package. This is for example the case of pandoc,
https://aur.archlinux.org/packages/pandoc-bin/
It pull from the official pandoc linux releases, 
https://github.com/jgm/pandoc/releases/
It's not an "official" distributed Arch package, but users can check and trust it by looking at the build recipe (PKGBUILD).

So to build a "paperboy-bin" on Arch, all we would need was to pull a binary from your ,
https://github.com/2mol/pboy/releases
and package it for Arch.
Except for the libtinfo5 thing, that is stopping the show.

Acording to, https://packages.debian.org/buster/libtinfo5
>  legacy version of the shared low-level terminfo library.

So my question is, what is it really that makes paperboy depend on an old libtinfo version ? Is it expectable that you could one day link it to the current libtinfo/ncurses that is installed on modern distros ? How much work would that involve ?

Thanks in advance.

Related:
https://github.com/2mol/pboy/issues/34
https://github.com/2mol/pboy/pull/36

**Comment by 2mol** [comment]
Hi, thank you very much for the detailed look into packaging!

I agree that there is no reason to depend on the old libtinfo, I suspect that this is a dependency of a library that we use for the commandline UI.

I will look into this and get back to you.

Cheers!

**Comment by 2mol** [comment]
@m040601 could you please try simlinking `libtinfo.so.6` to `libtinfo.so.5`? SHould be possible like so:

```
ln -s /usr/lib/libtinfo.so.6 /usr/lib/libtinfo.so.5
```

**Comment by m040601** [comment]
> could you please try simlinking

No. Sorry. That's exactly the kind of hacks I tried to explain that borks a clean and modern system, and prevents creating an official accepted package for it. Yes it might definetly work, but nobody will want to make this kind of changes just because of one software package.

Libtinfo is one of the dependencies of ncurses. Ncurses is such an important package, so much depends on it. Can you imagine the possible mess it can cause messing with the version of libtinfo ?
 
I'm sorry, I can't help you with the programming. I'm no Haskell expert.

**Comment by 2mol** [comment]
> No. Sorry. That's exactly the kind of hacks I tried to explain that borks a clean and modern system, and prevents creating an official accepted package for it. Yes it might definetly work, but nobody will want to make this kind of changes just because of one software package.

I understand (and agree), however my intention was mostly to learn if it works, and then to see where to go from there.

> Libtinfo is one of the dependencies of ncurses. Ncurses is such an important package, so much depends on it. Can you imagine the possible mess it can cause messing with the version of libtinfo ?

Sure, but symlinking 6 back to 5 shouldn't break any libraries that use either `libtinfo.so.6` or plain `libtinfo.so`

> I'm sorry, I can't help you with the programming. I'm no Haskell expert.

As a last option (for you specifically) I can suggest to install `ncurses5-compat-libs` from AUR.

In the meantime I will continue some experiments with static linking and ask around where the dependency comes from in the first place.

I'm also very keen to not have a `pboy` source package in AUR (I remember the horror of all the Haskell deps), and instead provide a simple binary package. Maybe it's ok to create a package for now with a dependency to `ncurses5-compat-libs`, if that solves the issue.

**Comment by 2mol** [comment]
we compile static linux binaries now thanks to #46 , which fixes this issue and lays the path for proper distro packages!

**Comment by m040601** [comment]
Can confirm. The released binary  works perfectly now on ArchLinux.
Thanks for all your effort.
