### ISSUE TITLE
dangling symlink causes pboy to crash

### ISSUE THREAD

**Issue by juhp** [2mol/pboy#44]
This should be pretty easy to fix - I just tried pboy for the first time and due to a download tool of mine (dl-fedora) I create some symlinks in my Downloads/ sometimes - later if I delete some of the big files I may forget to delete the accompanying symlink I made.

Anyway too much info... TL;DR: pboy should just ignore any dangling symlinks.

**Comment by 2mol** [comment]
Good to know, thanks for reporting!

I'll try to replicate it and see if I can understand what happens. Alternatively I will just wrap `getFileInfo` in `Lib.hs` in a catch block :)

**Comment by 2mol** [comment]
could you try again with the `1.4` branch? If you don't mind compiling from source.

**Comment by juhp** [comment]
Thanks it is fixed in dev-1.4 (actually I was testing the master branch when I reported).

BTW `resolver: lts-14.27` and `cabal-version: 3.0` are in conflict.
