### ISSUE TITLE
"Killed: 9"

### ISSUE THREAD

**Issue by atobi16** [2mol/pboy#49]
I pulled this down from Homebrew just now, and it doesn't appear to run correctly.
All it outputs is `Killed: 9` and stops.
```
                    'c.          atobi16@Arons-MBP.home 
                 ,xNMM.          ---------------------- 
               .OMMMMo           OS: macOS Big Sur 11.0.1 20B50 x86_64 
               OMMM0,            Host: MacBookPro16,1 
     .;loddo:' loolloddol;.      Kernel: 20.1.0 
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 13 days, 10 hours, 34 mins 
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 167 (brew) 
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: bash 5.0.18 
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1792x1120@2x 
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua 
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor 
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Light) 
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: Apple_Terminal 
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: Iosevka-Fixed-Thin 
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Intel i9-9880H (16) @ 2.30GHz 
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Intel UHD Graphics 630, AMD Radeon Pro 5500M 
       .cooc,.    .,coo:.        Memory: 8980MiB / 16384MiB 

                                                         
                                                         
```

**Comment by tech189** [comment]
I am getting a similar error after installing with homebrew: 
```
zsh: killed     pboy
```
Also on Big Sur if that helps.

**Comment by 2mol** [comment]
Very odd, thanks for reporting this! I will see if I can reproduce it, I guess I have to upgrade to Big Sur first :)

**Comment by 2mol** [comment]
@atobi16 , @tech189 Please try updating via homebrew now (should give you pboy version 1.5). There was a bug in a previous version of the binary compression tool UPX, so this new pboy release should be fine on Big Sur.

Let me know if it works!

**Comment by tech189** [comment]
Still getting the same error unfortunately :/
I tried running dmesg to grep any reasons for killing the process but couldn't find anything

**Comment by 2mol** [comment]
I just released 1.6, please update and let me know if that fixed it.

**Comment by kepler471** [comment]
> I just released 1.6, please update and let me know if that fixed it.

This works! both on arm64 and x86_64 through Rosetta. Thanks a lot, and keep up the good work!!!

**Comment by 2mol** [comment]
awesome! thank you for testing so fast :)

**Comment by tech189** [comment]
Fixed for me too, thanks!
